FROM python:3.11

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY inference.py .
COPY model_utils.py .
COPY model/ ./model/

ENTRYPOINT ["python", "inference.py"]