replicaCount: 1

image:
  repository: aiops-quality-service
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 8000

env:
  MODEL_PATH: "model/model.pkl"
  RETRAIN_WEBHOOK_URL: ""

